# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='word1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1', to='words.Word'),
        ),
        migrations.AddField(
            model_name='association',
            name='word2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2', to='words.Word'),
        ),
    ]
